name: Deploy dev environment

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Code linting
        run: npm run lint
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Inject envs
        run: |
          echo "" > .env
          echo "VITE_ECSB_MOVEMENT_WS_API_URL=$VITE_ECSB_MOVEMENT_WS_API_URL" >> .env
          echo "VITE_ECSB_CHAT_WS_API_URL=$VITE_ECSB_CHAT_WS_API_URL" >> .env
          echo "VITE_ECSB_HTTP_AUTH_AND_MANAGEMENT_API_URL=$VITE_ECSB_HTTP_AUTH_AND_MANAGEMENT_API_URL" >> .env
          echo "VITE_ECSB_LOBBY_WS_API_URL=$VITE_ECSB_LOBBY_WS_API_URL" >> .env
        env:
          VITE_ECSB_MOVEMENT_WS_API_URL: ${{ vars.VITE_DEV_ECSB_MOVEMENT_WS_API_URL }}
          VITE_ECSB_CHAT_WS_API_URL: ${{ vars.VITE_DEV_ECSB_CHAT_WS_API_URL }}
          VITE_ECSB_HTTP_AUTH_AND_MANAGEMENT_API_URL: ${{ vars.VITE_DEV_ECSB_HTTP_AUTH_AND_MANAGEMENT_API_URL }}
          VITE_ECSB_LOBBY_WS_API_URL: ${{ vars.VITE_DEV_ECSB_LOBBY_WS_API_URL }}
      - name: Build files
        run: npm run build
      - name: copy files via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: 'dist/*,assets/'
          target: ~/dev_source
